name: Build Vue
on:
  push:
    branches:
      - production
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: ${{ github.repository_owner }}
        reponame: 'seabats'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        gitemail: "3743342+schnerring@users.noreply.github.com"
        gitname: "schnerring"
